### ISSUE TITLE
3.1 Modelo Relacional

### ISSUE THREAD

**Issue by jrsosago** [ISWPOLI/Historias#14]
**Descripción**
Modelo Relacional, tiene las siguientes historias asociadas:
- [x] Modelo. Issue #15.
- [x] Pruebas- Insert. Issue #16.
- [x] Servidor Infraestructura. Issue #17.
- [x] Insert Base de datos. Issue #48.

**Comment by jrsosago** [comment]
Se cierra está característica por tareas terminadas.
